# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8855bbd2f6b62af4ff921ad65ae0246ad7e6622504336698c20114ab20e938aab982b3141c5e94746401ac3d2421f469ce2979320e936ba046c10142cf0100c5

test:
  secret_key_base: a344116f008d3fbc897ca43581a5640528e89033de71e9c51579a67a5e14a9c334ac8e00a8e6e0a629257782a55a6093263b1a130b07bedfa8ce87d39c5da433

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
